INSERT INTO category (name, created_at) VALUES ('Jazz', NOW());
INSERT INTO category (name, created_at) VALUES ('Pop', NOW());
INSERT INTO category (name, created_at) VALUES ('Rock', NOW());
INSERT INTO category (name, created_at) VALUES ('Chill', NOW());
INSERT INTO category (name, created_at) VALUES ('Rap', NOW());
INSERT INTO category (name, created_at) VALUES ('Classical', NOW());
INSERT INTO category (name, created_at) VALUES ('Country', NOW());
INSERT INTO category (name, created_at) VALUES ('Blues', NOW());
INSERT INTO category (name, created_at) VALUES ('Reggae', NOW());
INSERT INTO category (name, created_at) VALUES ('Electronic', NOW());
INSERT INTO category (name, created_at) VALUES ('Metal', NOW());

INSERT INTO product (name, price, img_url, date) VALUES ('The Best of Miles Davis', 9.99, 'https://picsum.photos/200', NOW());
INSERT INTO product (name, price, img_url, date) VALUES ('The Best of The Beatles', 9.99, 'https://picsum.photos/200', NOW());
INSERT INTO product (name, price, img_url, date) VALUES ('The Best of The Rolling Stones', 9.99, 'https://picsum.photos/200', NOW());
INSERT INTO product (name, price, img_url, date) VALUES ('The Best of Bob Marley', 9.99, 'https://picsum.photos/200', NOW());
INSERT INTO product (name, price, img_url, date) VALUES ('The Best of Eminem', 9.99, 'https://picsum.photos/200', NOW());
INSERT INTO product (name, price, img_url, date) VALUES ('The Best of Beethoven', 9.99, 'https://picsum.photos/200', NOW());
INSERT INTO product (name, price, img_url, date) VALUES ('The Best of Johnny Cash', 9.99, 'https://picsum.photos/200', NOW());
INSERT INTO product (name, price, img_url, date) VALUES ('The Best of B.B. King', 9.99, 'https://picsum.photos/200', NOW());
INSERT INTO product (name, price, img_url, date) VALUES ('The Best of Daft Punk', 9.99, 'https://picsum.photos/200', NOW());
INSERT INTO product (name, price, img_url, date) VALUES ('The Best of Metallica', 9.99, 'https://picsum.photos/200', NOW());

INSERT INTO product_category (product_id, category_id) VALUES (1, 1);
INSERT INTO product_category (product_id, category_id) VALUES (2, 2);
INSERT INTO product_category (product_id, category_id) VALUES (2, 3);
INSERT INTO product_category (product_id, category_id) VALUES (3, 3);
INSERT INTO product_category (product_id, category_id) VALUES (3, 8);
INSERT INTO product_category (product_id, category_id) VALUES (4, 9);
INSERT INTO product_category (product_id, category_id) VALUES (5, 5);
INSERT INTO product_category (product_id, category_id) VALUES (6, 6);
INSERT INTO product_category (product_id, category_id) VALUES (7, 7);
INSERT INTO product_category (product_id, category_id) VALUES (8, 8);
INSERT INTO product_category (product_id, category_id) VALUES (9, 10);
INSERT INTO product_category (product_id, category_id) VALUES (10, 11);